spring:
  thymeleaf:
    enabled: true  #开启thymeleaf视图解析
    encoding: utf-8  #编码
    prefix: classpath:/templates/  #前缀
    cache: false  #是否使用缓存
    mode: HTML5  #严格的HTML语法模式
    suffix: .html  #后缀名

  datasource:
    url: jdbc:postgresql://10.211.55.4:5432/ill?useSSL=false
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      write-dates-as-timestamps: false

mybatis-plus:
  type-aliases-package: com.sanguo.mapper
  mapper-locations: classpath*:/mapper/**/*.xml